# Generated by Django 4.2.11 on 2024-06-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_items",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
